language: python 
python: 
- "3.6"
env: 
  - DJANGO_SETTINGS_MODULE="decide.settings"
before_install: 
- cd decide
install: 
- pip install -r requirements.txt
services:
  - postgresql

global:
  - PGPORT=5432

before_script:
 - cp local_settings.travis.py local_settings.py
 - psql -c "create user decide with password 'decide'" 
 - psql -c "create database decide owner decide"
 - python manage.py migrate

script: 
- python manage.py test store

addons:
  postgresql: "9.6"


